### ISSUE TITLE
[Scala 3] Roadmap to Scala 3 release

### ISSUE THREAD

**Issue by TimWSpence** [typelevel/kittens#481]
Required:
- [x] [Always require `Or` instances for `given`s ](https://github.com/typelevel/kittens/issues/477)
- [x] [`implicit` keyword in scala 3 tests](https://github.com/typelevel/kittens/issues/474)
- [x] [Wildcard import derivation not working](https://github.com/typelevel/kittens/issues/425)
- [x] [Derive `ShowPretty`](https://github.com/typelevel/kittens/issues/488)
- [x] [Test derivation for enums](https://github.com/typelevel/kittens/issues/495)
- [x] [Make instances `Serializable`](https://github.com/typelevel/kittens/issues/496)

Optional/under discussion:
- [ ] [Derivation for deeply nested types](https://github.com/typelevel/kittens/issues/473)
- [ ] [Extra `Covariant` and `Invariant` instances](https://github.com/typelevel/kittens/issues/479)
- [ ] [Stack safety of derived instances](https://github.com/typelevel/kittens/issues/476)
- [ ] [Sequence support](https://github.com/typelevel/kittens/issues/482)
- [ ] [Derive `ConsK`](https://github.com/typelevel/kittens/issues/489)

**Comment by TimWSpence** [comment]
> IMO stack safety and sequence support are not blocking. One of the issues with stack safety (at least the way it was done with `Eval` in Scala 2) is that it comes at a cost even when you don't need it. And in theory it could apply to any nested derivation, not just `Functor` and `Foldable`.

Yeah definitely. Woops, I meant to update that ticket to say that it isn't an exhaustive list of derivations that aren't stacksafe 🤦  One option I was considering is if we offered a separate `semiauto.stackSafeFunctor` that goes through `Eval`? (So no `auto` or `derives` syntax) I _think_ that would work but I guess we'd effectively be maintaining two derivations per typeclass which would suck

**Comment by joroKr21** [comment]
Yeah it's not great to maintain two derivations. Also a derivation based on `Eval` is complex because we have to duplicate all method signatures and match on the runtime type of the type class.

**Comment by joroKr21** [comment]
I will close this now that 3.0 is out. We can tackle the remaining issues independently.
